### ISSUE TITLE
Torch compile broken on PyTorch Main

### ISSUE THREAD

**Issue by drisspg** [pytorch-labs/float8_experimental#176]
# Repro

`pytest test/test_compile.py`

```Shell
msg = "call_function BuiltinVariable(getattr) [TorchInGraphFunctionVariable(<class 'float8_experimental.float8_tensor.Float8Tensor'>), ConstantVariable(str)] {}"

    def unimplemented(msg: str) -> NoReturn:
        assert msg != os.environ.get("BREAK", False)
>       raise Unsupported(msg)
E       torch._dynamo.exc.Unsupported: call_function BuiltinVariable(getattr) [TorchInGraphFunctionVariable(<class 'float8_experimental.float8_tensor.Float8Tensor'>), ConstantVariable(str)] {}
E       
E       from user code:
E          File "/home/drisspg/meta/float8_experimental/float8_experimental/dynamic_linear/dynamic_float8_linear.py", line 53, in forward
E           x_fp8 = self.cast_to_float8(x)
E         File "/home/drisspg/meta/float8_experimental/float8_experimental/dynamic_linear/dynamic_float8_linear.py", line 73, in cast_to_float8
E           return Float8Tensor.to_float8(
E       
E       Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
E       
E       
E       You can suppress this exception and fall back to eager by setting:
E           import torch._dynamo
E           torch._dynamo.config.suppress_errors = True

../../miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/exc.py:193: Unsupported
```

This is caused because there is a new graphbreak in the to_float8 method.
```Shell
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG] Graph break: call_function BuiltinVariable(getattr) [TorchInGraphFunctionVariable(<class 'float8_experimental.float8_tensor.Float8Tensor'>), ConstantVariable(str)] {} from user code at:
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]   File "/home/drisspg/meta/ao_benchmarks/llama/model.py", line 164, in forward
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]     h = x + self.attention(self.attention_norm(x), freqs_cis)
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]     return forward_call(*args, **kwargs)
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]   File "/home/drisspg/meta/ao_benchmarks/llama/model.py", line 196, in forward
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]     q, k, v = self.wqkv(x).split([self.dim, kv_size, kv_size], dim=-1)
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]     return forward_call(*args, **kwargs)
[2024-01-02 15:03:04,866] [1/0] torch._dynamo.symbolic_convert.__graph_breaks: [DEBUG]   File "/home/drisspg/meta/float8_experimental/float8_experimental/dynamic_linear/dynamic_float8_linear.py", line 53, in forward
```

**Comment by drisspg** [comment]
@yanboliang suggested the torch._dynamo.allow_in_graph here: 


This resulted in 
```Shell
            ) from ex
E           torch._dynamo.exc.Unsupported: speculate_subgraph: while introspecting autograd.Function, we were unable to trace function `backward` into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown. Scroll up for the stack trace of the initial exception. The reason was: call_function UserDefinedClassVariable() [TensorVariable(), TensorVariable(), ConstantVariable(dtype)] {'emulate': ConstantVariable(bool)}
E           
E           from user code:
E              File "/home/drisspg/meta/float8_experimental/float8_experimental/dynamic_linear/dynamic_float8_linear.py", line 62, in forward
E               y = self.cast_to_float8e5m2_bw(y)
E             File "/home/drisspg/meta/float8_experimental/float8_experimental/dynamic_linear/dynamic_float8_linear.py", line 78, in cast_to_float8e5m2_bw
E               return NoopFwToFloat8E5M2Bw.apply(gradY, self.emulate)
E           
E           Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
E           
E           
E           You can suppress this exception and fall back to eager by setting:
E               import torch._dynamo
E               torch._dynamo.config.suppress_errors = True

../../miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/higher_order_ops.py:328: Unsupported
---------------------------------------- Captured stderr call -----------------------------------------
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [WARNING] speculate_subgraph: while introspecting autograd.Function, we were unable to trace function `backward` into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown.
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR] call_function UserDefinedClassVariable() [TensorVariable(), TensorVariable(), ConstantVariable(dtype)] {'emulate': ConstantVariable(bool)}
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR] Traceback (most recent call last):
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/higher_order_ops.py", line 256, in speculate_subgraph
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     output = f.call_function(tx, args, sub_kwargs)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 255, in call_function
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return super().call_function(tx, args, kwargs)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 84, in call_function
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return tx.inline_user_function_return(
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 650, in inline_user_function_return
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2245, in inline_call
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return cls.inline_call_(parent, func, args, kwargs)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2354, in inline_call_
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     tracer.run()
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 780, in run
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     and self.step()
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in step
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     getattr(self, inst.opname)(inst)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 462, in wrapper
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return inner_fn(self, inst)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1241, in CALL_FUNCTION_KW
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     self.call_function(fn, args, kwargs)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 644, in call_function
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     self.push(fn.call_function(self, args, kwargs))
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/user_defined.py", line 398, in call_function
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return super().call_function(tx, args, kwargs)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 321, in call_function
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     unimplemented(f"call_function {self} {args} {kwargs}")
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 193, in unimplemented
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     raise Unsupported(msg)
[2024-01-02 15:15:31,233] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR] torch._dynamo.exc.Unsupported: call_function UserDefinedClassVariable() [TensorVariable(), TensorVariable(), ConstantVariable(dtype)] {'emulate': ConstantVariable(bool)}
```

**Comment by yanboliang** [comment]
```Float8Tensor``` is a custom Tensor class, though we support is as autograd.Function output in eager mode, but we don't support it in compile mode yet. The work around is put this autograd.Function allowed in graph.
