### ISSUE TITLE
Issue with running isnan and _is_any_true with Float8Tensor

### ISSUE THREAD

**Issue by snarayan21** [pytorch-labs/float8_experimental#226]
Hi, I've implemented a custom autograd function that does nothing on the forwards pass and casts the gradient to FP8E5M2 in the backwards pass, very similar to the autograd functions in Float8Linear. I'm running into the error below -- is this because maybe the input tensor has NaN values, or does `aten.isnan.default` have to be implemented for Float8Tensor? I'm also seeing the same error but for `aten._is_any_true.default`.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2160, in _train_loop
    total_loss_dict = self._train_batch(use_grad_scaling)
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2347, in _train_batch
    self._train_microbatches(microbatches, total_loss_dict)
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2447, in _train_microbatches
    microbatch_loss_dict = self._train_microbatch(use_grad_scaling, current_batch_size, is_final_microbatch)
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2576, in _train_microbatch
    microbatch_loss.backward(create_graph=self._backwards_create_graph)
  File "/usr/lib/python3/dist-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/usr/lib/python3/dist-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/usr/lib/python3/dist-packages/torch/autograd/graph.py", line 690, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/lib/python3/dist-packages/float8_experimental/float8_tensor.py", line 173, in __torch_dispatch__
    raise NotImplementedError(f"attempting to run {func}, this is not supported")
NotImplementedError: attempting to run aten.isnan.default, this is not supported
```
Thanks!

**Comment by snarayan21** [comment]
Hey, just wanted to follow up on this!

**Comment by drisspg** [comment]
Those two ops are currently not supported, do you have standalone repro, and I can take a look

**Comment by snarayan21** [comment]
I got around this by adding `aten.isnan.default` to the list [here](https://github.com/pytorch-labs/float8_experimental/blob/31877bbc778f5dae3eec820f9ae96c09ec8b161a/float8_experimental/float8_ops.py#L43) and `aten._is_any_true.default` to the list [here](https://github.com/snarayan21/float8_experimental/blob/d9422063e7ea9fe6b8791878dde5ebbdd225b706/float8_experimental/float8_ops.py#L48). Not sure if this is the right fix though.

**Comment by drisspg** [comment]
yup those look right!

**Comment by vkuzo** [comment]
closing since you fixed it, please feel free to open an issue in https://github.com/pytorch/ao/tree/main/torchao/float8 if you need upstream
